https://api.mapbox.com/geocoding/v5/mapbox.places/La%20Paz.json?country=bo&proximity=ip&language=es&access_token=pk.eyJ1IjoiYXJpZWxzY2MiLCJhIjoiY2xtNXE3MmpjMDB4azNqa2huOGxzcmxpOSJ9.WKL5AWpWH-iQy7ROzGzVdg
